switch from positional to named argparse argument
Traceback (most recent call last):
  File "convert.py", line 91, in <module>
    with open(sys.argv[1]) as f:
FileNotFoundError: [Errno 2] No such file or directory: '--filename'